# Dataworks lineage log config
# default same as LOG_DIR
# lineage_dataworks_log_dir=
lineage_dataworks_roll_num=90
lineage_dataworks_roll_maxsize=1024
lineage_dataworks_log_roll_interval=DAY
lineage_dataworks_log_delete_age=30d
lineage_dataworks_sys_accumulated_file_size=4

# Dataworks lineage collection scope: table, column, table,column or empty (disabled)
lineage_dataworks_enabled_scope=table,column
